env:
    rclone_config: "ENCRYPTED[c0d1ee032728b1b5358ab3d5864f6e66e9a0c04c63ecb41c611ae766739861c0759514566e1a24b58bb8c072ccb8771c]"
    url: "https://anu.inok189.workers.dev/nusantara/ccache.tar.gz"
    repo_rom: "https://github.com/hentaiOS/platform_manifest"
    repo_device: "https://github.com/WalkingDead3/android_device_xiaomi_juice"
    repo_vendor: "https://github.com/WalkingProjekt-juice/android_vendor_xiaomi_juice"
task:
    name: Build
    timeout_in: 480m
    container:
      image: walkingdead666/android:latest
      cpu: 8
      memory: 32G
    
    Sync_script:
        - mkdir -p ~/.config/rclone
        - echo "$rclone_config" > ~/.config/rclone/rclone.conf
        - df -h && free -h && nproc && cat /etc/os* && env
        - mkdir -p /tmp/rom
        - cd /tmp/rom
        - repo init -u $repo_rom -b Rika     
        - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        - git clone $repo_device --depth 1 -b 11.0 device/xiaomi/juice
        - git clone $repo_vendor --depth 1 -b 11 vendor/xiaomi/juice 
    Build_script:
        - bash build.sh
    
