env:
    rclone_config: "ENCRYPTED[c0d1ee032728b1b5358ab3d5864f6e66e9a0c04c63ecb41c611ae766739861c0759514566e1a24b58bb8c072ccb8771c]"

task:
    name: Sync/Build/Upload...
    timeout_in: 2h
    container:
      image: walkingdead666/android:latest
      cpu: 8
      memory: 32G
    
    Sync_script:
        - mkdir -p ~/.config/rclone
        - echo "$rclone_config" > ~/.config/rclone/rclone.conf
        - df -h && free -h && nproc && cat /etc/os* && env
        - mkdir -p /tmp/WeebProjekt
        - cd /tmp/WeebProjekt
        - repo init --depth=1 --no-repo-verify -u https://github.com/WeebProjekt/platform_manifest -b reborn -g default,-mips,-darwin,-notdefault
        - git clone https://github.com/WalkingProjekt-juice/manifest --depth 1 -b reborn .repo/local_manifests
        - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
        - rm -rf device/generic/opengl-transport
    Build_script:
        - bash build.sh
    
