env:
    rclone_config: "ENCRYPTED[c0d1ee032728b1b5358ab3d5864f6e66e9a0c04c63ecb41c611ae766739861c0759514566e1a24b58bb8c072ccb8771c]"
         
task:
    name: Build
    timeout_in: 480m
    container:
      image: walkingdead666/android:latest
      cpu: 8
      memory: 32G

    Build-Sync-Upload-script:
        - bash build.sh
    
