env:
    rclone_config: "ENCRYPTED[be8a27ae4fb88678d3799d29d00434a9564ee7ede094312184c3b1453e6a5abdb9c25d69d4f58d9db24d9abfcdd724a2]"
         
task:
    name: Telegram Info
    container:
        image: walkingdead666/android-builder:latest
        cpu: 6
        memory: 4G
        
    informationbot_script:
         - bash InfoTG.sh     
task:
    name: Build
    container:
      image: walkingdead666/android-builder:latest
      cpu: 8
      memory: 32G

    download_ccache_script:
        - bash download-ccache.sh

    config_script:
        - bash config-cirrus.sh
        
    build_rom_script:
        - bash build_rum.sh
    
