env:
    rclone_config: "ENCRYPTED[be8a27ae4fb88678d3799d29d00434a9564ee7ede094312184c3b1453e6a5abdb9c25d69d4f58d9db24d9abfcdd724a2]"
    
task:
    name: InfoTG
    timeout_in: 2m
    container:
        image: walkingdead666/anu:latest
        cpu: 2
        memory: 4G
      
    curl_telegram_script:
        - bash curl_telegram.sh  # Отсылает информацию о сборке в Telegram      
task:
    name: Build
    timeout_in: 120m
    container:
      image: walkingdead666/anu:latest
      cpu: 8
      memory: 32G

    download_ccache_script:
        - df -h
        - free -h
        - nproc
        - cat /etc/os*
        - env
        - url=https://roms.apon77.workers.dev/ccache/ci3/ccache.tar.gz
        - cd /tmp
        - time aria2c $url -x16 -s50
        - time tar xf ccache.tar.gz
        - rm -rf ccache.tar.gz

    config_script:
        # Configuring git
        - mkdir -p /tmp/rom
        - cd /tmp/rom
        - git config --global user.email "lexaxx14@gmail.com"
        - git config --global user.name "WalkingDead3"
        - git config --global color.ui "true"
        # Repo Init/Sync
        - repo init -q --no-repo-verify --depth=1 -u git://github.com/LineageOS/android.git -b lineage-18.1 -g default,-device,-mips,-darwin,-notdefault
        - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
        # Clone DT/VT/KT/TC
        - git clone https://github.com/WalkingDead3/device_xiaomi_juice -b anu device/xiaomi/juice
        - git clone --depth=1 https://gitlab.com/I-n-o-k/vendor-lime --single-branch -b 11 vendor/xiaomi/juice
        - git clone --depth=1 https://github.com/I-n-o-k/android_kernel_xiaomi_bengal --single-branch -b 11.0 kernel/xiaomi/juice
        - git clone --depth=1 https://github.com/kdrag0n/proton-clang --single-branch -b master prebuilts/clang/host/linux-x86/clang-proton
         
    build_rom_script:
        - cd /tmp/rom
        - source build/envsetup.sh
        - lunch lineage_juice-userdebug
        - export CCACHE_DIR=/tmp/ccache
        - export CCACHE_EXEC=$(which ccache)
        - export USE_CCACHE=1
        - ccache -M 20G
        - ccache -o compression=true
        - ccache -z
        - make bacon
        - cd /tmp
        - rclone copy /tmp/rom/out/target/product/juice/Lineage*.zip WalkingDead:juice -P
    
