env:
    rclone_config: "ENCRYPTED[c0d1ee032728b1b5358ab3d5864f6e66e9a0c04c63ecb41c611ae766739861c0759514566e1a24b58bb8c072ccb8771c]"
         
task:
    name: Build
    timeout_in: 480m
    container:
      image: walkingdead666/android:latest
      cpu: 8
      memory: 32G
    
    Sync_script:
        - mkdir -p /tmp/rom
        - cd /tmp/rom
        - repo init --depth=1 --no-repo-verify -u https://github.com/ResurrectionRemix/platform_manifest.git -b Q
        - git clone https://github.com/WalkingDead3/manifest.git --depth 1 -b RR .repo/local_manifests
        - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    Build-Sync-Upload-script:
        - bash build.sh
    
