env:
    rclone_config: "ENCRYPTED[c0d1ee032728b1b5358ab3d5864f6e66e9a0c04c63ecb41c611ae766739861c0759514566e1a24b58bb8c072ccb8771c]"
    url: "https://anu.inok189.workers.dev/nusantara/ccache.tar.gz"
    # Repo ROM
    repo_rom: "https://github.com/hentaiOS/platform_manifest"
    # Repo DT/VT/KT/Clang
    repo_device: "https://github.com/WalkingDead3/android_device_xiaomi_juice"
    repo_vendor: "https://github.com/WalkingProjekt-juice/android_vendor_xiaomi_juice"
    repo_kernel: "https://github.com/WalkingProjekt-juice/android_kernel_xiaomi_bengal"
    repo_clang: "https://github.com/WalkingProjekt-juice/proton-clang"
    # Path DT/VT/KT/Clang
    path_device: "device/xiaomi/juice"
    path_kernel: "kernel/xiaomi/juice"
    path_vendor: "vendor/xiaomi/juice"
    path_clang: "prebuilts/clang/host/linux-x86/clang-proton"

task:
    name: Build
    timeout_in: 480m
    container:
      image: walkingdead666/android:latest
      cpu: 8
      memory: 32G
    
    Sync_script:
        - mkdir -p ~/.config/rclone
        - echo "$rclone_config" > ~/.config/rclone/rclone.conf
        - df -h && free -h && nproc && cat /etc/os* && env
        - mkdir -p /tmp/rom
        - cd /tmp/rom
        - repo init -u $repo_rom -b Rika     
        - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        - git clone $repo_device --depth 1 -b 11.0 $path_device
        - git clone $repo_vendor --depth 1 -b 11 $path_vendor
        - git clone $repo_kernel -b 11.0 $path_kernel
        - git clone $repo_clang --depth 1 -b master $path_clang
    Build_script:
        - bash build.sh
    
